travis:
  secure:
    BINSTAR_TOKEN: ktFTPtr8u52cj/yZyFe0kXnOaI757FFpvEqbDDKcL+aDXt4ux8OUQNGv8c2SQmFHAsbKHNKdKJViNtNcarl6r3qKM1C1HM7pvXK6zJ3qou9CbJrZg1pNOnNdNU9x5EY8U0hrp3rMZconvUVtz2wfFvmkZRVaP1s9vqZl9+TY1CQzrdbXsM11eSS3Mfbqa9oxwomz67Tq1iZEF0hB7SJW8nUoBMwh1P1wxXDlhVQsU7hUk41ArprUJfZX9Fo3x/52OV6MlibkgorAewHR4e2Q9VO93WMAP9F4s497jbQ0y05kNK6uTWtJSH9Oy7sKpKJ8e0/ij9UdnCwCVe7fIBIa4dzA3sdcgNo9S5677qVauCfg9ehEXLxyj0YCxUnkAan1+sChpp36OFQIDISS2DSHiLs5OxSSOSsH1Ss7wTR0BMwEDAq43fBiCKl4eWJeYSh96U8Dd9F/kCvvVW4xM4XHaNJrlaNsqW4TNdeP9jFYMSTKW6FgY5At1ikpJBMjysWebjiRXEK7b30aOIO/rE8bTRKP+MxUF+PgVxhD7vl25pLKUZO0JM2NxL6w/qxtZY3cXNPRzkDI+wWPXimnnTCDIPK+NCqfzER9QjUcVtPQ0QtQrKFN8ddui9kP4XgvJJBmms10/c7jfySQz3e0CDd1YgucjQvG98Ma2vkLh4wgnyc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
